FROM node:20-alpine AS build

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --production

COPY . .

RUN yarn build

FROM node:20-alpine AS production

WORKDIR /app

COPY --from=build /app/build ./

RUN yarn global add serve

EXPOSE 3000

ENV NODE_ENV=production

CMD ["serve", "-s", "."]